[workspace]
resolver = "2"
members = [
    "crates/rnumpy",
    "crates/rscipy",
    "crates/rpandas",
    "crates/rustorch",
    "crates/parity_runner",
]
default-members = [
    "crates/rnumpy",
    "crates/rscipy",
    "crates/rpandas",
    "crates/rustorch",
    "crates/parity_runner",
]

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
